/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubirRouteImport } from './routes/subir'
import { Route as ApiBuscarRouteImport } from './routes/api/buscar'
import { Route as ApiClasificarRouteImport } from './routes/api/clasificar'
import { Route as ApiContenidoRouteImport } from './routes/api/contenido'
import { Route as ApiContenidoArchivoRouteImport } from './routes/api/contenido-archivo'
import { Route as ApiContenidoDocumentoIdRouteImport } from './routes/api/contenido.$documentoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubirRoute = SubirRouteImport.update({
  id: '/subir',
  path: '/subir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuscarRoute = ApiBuscarRouteImport.update({
  id: '/api/buscar',
  path: '/api/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClasificarRoute = ApiClasificarRouteImport.update({
  id: '/api/clasificar',
  path: '/api/clasificar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContenidoRoute = ApiContenidoRouteImport.update({
  id: '/api/contenido',
  path: '/api/contenido',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContenidoArchivoRoute = ApiContenidoArchivoRouteImport.update({
  id: '/api/contenido-archivo',
  path: '/api/contenido-archivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContenidoDocumentoIdRoute = ApiContenidoDocumentoIdRouteImport.update({
  id: '/$documentoId',
  path: '/$documentoId',
  getParentRoute: () => ApiContenidoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subir': typeof SubirRoute
  '/api/buscar': typeof ApiBuscarRoute
  '/api/clasificar': typeof ApiClasificarRoute
  '/api/contenido': typeof ApiContenidoRouteWithChildren
  '/api/contenido-archivo': typeof ApiContenidoArchivoRoute
  '/api/contenido/$documentoId': typeof ApiContenidoDocumentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subir': typeof SubirRoute
  '/api/buscar': typeof ApiBuscarRoute
  '/api/clasificar': typeof ApiClasificarRoute
  '/api/contenido': typeof ApiContenidoRouteWithChildren
  '/api/contenido-archivo': typeof ApiContenidoArchivoRoute
  '/api/contenido/$documentoId': typeof ApiContenidoDocumentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subir': typeof SubirRoute
  '/api/buscar': typeof ApiBuscarRoute
  '/api/clasificar': typeof ApiClasificarRoute
  '/api/contenido': typeof ApiContenidoRouteWithChildren
  '/api/contenido-archivo': typeof ApiContenidoArchivoRoute
  '/api/contenido/$documentoId': typeof ApiContenidoDocumentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/sitemap.xml'
    | '/subir'
    | '/api/buscar'
    | '/api/clasificar'
    | '/api/contenido'
    | '/api/contenido-archivo'
    | '/api/contenido/$documentoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/sitemap.xml'
    | '/subir'
    | '/api/buscar'
    | '/api/clasificar'
    | '/api/contenido'
    | '/api/contenido-archivo'
    | '/api/contenido/$documentoId'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/sitemap.xml'
    | '/subir'
    | '/api/buscar'
    | '/api/clasificar'
    | '/api/contenido'
    | '/api/contenido-archivo'
    | '/api/contenido/$documentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubirRoute: typeof SubirRoute
  ApiBuscarRoute: typeof ApiBuscarRoute
  ApiClasificarRoute: typeof ApiClasificarRoute
  ApiContenidoRoute: typeof ApiContenidoRouteWithChildren
  ApiContenidoArchivoRoute: typeof ApiContenidoArchivoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subir': {
      id: '/subir'
      path: '/subir'
      fullPath: '/subir'
      preLoaderRoute: typeof SubirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buscar': {
      id: '/api/buscar'
      path: '/api/buscar'
      fullPath: '/api/buscar'
      preLoaderRoute: typeof ApiBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clasificar': {
      id: '/api/clasificar'
      path: '/api/clasificar'
      fullPath: '/api/clasificar'
      preLoaderRoute: typeof ApiClasificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contenido': {
      id: '/api/contenido'
      path: '/api/contenido'
      fullPath: '/api/contenido'
      preLoaderRoute: typeof ApiContenidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contenido-archivo': {
      id: '/api/contenido-archivo'
      path: '/api/contenido-archivo'
      fullPath: '/api/contenido-archivo'
      preLoaderRoute: typeof ApiContenidoArchivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contenido/$documentoId': {
      id: '/api/contenido/$documentoId'
      path: '/$documentoId'
      fullPath: '/api/contenido/$documentoId'
      preLoaderRoute: typeof ApiContenidoDocumentoIdRouteImport
      parentRoute: typeof ApiContenidoRoute
    }
  }
}

interface ApiContenidoRouteChildren {
  ApiContenidoDocumentoIdRoute: typeof ApiContenidoDocumentoIdRoute
}

const ApiContenidoRouteChildren: ApiContenidoRouteChildren = {
  ApiContenidoDocumentoIdRoute: ApiContenidoDocumentoIdRoute,
}

const ApiContenidoRouteWithChildren = ApiContenidoRoute._addFileChildren(
  ApiContenidoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubirRoute: SubirRoute,
  ApiBuscarRoute: ApiBuscarRoute,
  ApiClasificarRoute: ApiClasificarRoute,
  ApiContenidoRoute: ApiContenidoRouteWithChildren,
  ApiContenidoArchivoRoute: ApiContenidoArchivoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
