/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubirRouteImport } from './routes/subir'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentoIdRouteImport } from './routes/documento.$id'
import { Route as ApiBackendSplatRouteImport } from './routes/api/backend/$'

const SubirRoute = SubirRouteImport.update({
  id: '/subir',
  path: '/subir',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoIdRoute = DocumentoIdRouteImport.update({
  id: '/documento/$id',
  path: '/documento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackendSplatRoute = ApiBackendSplatRouteImport.update({
  id: '/api/backend/$',
  path: '/api/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subir': typeof SubirRoute
  '/documento/$id': typeof DocumentoIdRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subir': typeof SubirRoute
  '/documento/$id': typeof DocumentoIdRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subir': typeof SubirRoute
  '/documento/$id': typeof DocumentoIdRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/buscar'
    | '/sitemap.xml'
    | '/subir'
    | '/documento/$id'
    | '/api/backend/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/buscar'
    | '/sitemap.xml'
    | '/subir'
    | '/documento/$id'
    | '/api/backend/$'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/buscar'
    | '/sitemap.xml'
    | '/subir'
    | '/documento/$id'
    | '/api/backend/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  BuscarRoute: typeof BuscarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubirRoute: typeof SubirRoute
  DocumentoIdRoute: typeof DocumentoIdRoute
  ApiBackendSplatRoute: typeof ApiBackendSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subir': {
      id: '/subir'
      path: '/subir'
      fullPath: '/subir'
      preLoaderRoute: typeof SubirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento/$id': {
      id: '/documento/$id'
      path: '/documento/$id'
      fullPath: '/documento/$id'
      preLoaderRoute: typeof DocumentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backend/$': {
      id: '/api/backend/$'
      path: '/api/backend/$'
      fullPath: '/api/backend/$'
      preLoaderRoute: typeof ApiBackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  BuscarRoute: BuscarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubirRoute: SubirRoute,
  DocumentoIdRoute: DocumentoIdRoute,
  ApiBackendSplatRoute: ApiBackendSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
